language: node_js
node_js: "6"

sudo: required
dist: trusty

addons:
  apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable

cache:
    directories:
        - $HOME/.npm

before_install:
    - npm config set loglevel warn
    - npm install -g grunt-cli

install:
    - npm install

script:
    - grunt ci:travis
    - grunt build
