language: node_js
node_js: "6"

sudo: required
dist: trusty

addons:
  apt:
    packages:
        - google-chrome-stable

cache:
    directories:
        - $HOME/.cache/yarn

before_install:
    - yarn global add grunt-cli

script:
    - grunt ci:travis
    - grunt build
